dashboard_components: use fixed versions
dash 2.1.0 need Werkzeug 2.0.0 (plotly/dash #1992)
dash 2.6.0 throws some errors

diff --git a/projects/dashboard_components/bootstrap b/projects/dashboard_components/bootstrap
--- a/projects/dashboard_components/bootstrap
+++ b/projects/dashboard_components/bootstrap
@@ -1,9 +1,15 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-python3 -m venv venv
-. venv/bin/activate
-pip3 install wheel
-pip3 install -r requirements.txt
-pip3 install plotly dash pandas pyyaml
-npm install
+for p in wheel dash==2.1.0 plotly pandas pyyaml Werkzeug==2.0.0; do
+	ove-echo cyan "install python package '$p'"
+	if ! pip3 install --user --no-warn-script-location $p; then
+		ove-echo error "'pip3 install --user $p' failed"
+		exit 1
+	fi
+done
 
+ove-echo cyan "npm install"
+if ! npm install; then
+	ove-echo error "'npm install' failed"
+	exit 1
+fi
diff --git a/projects/dashboard_components/build b/projects/dashboard_components/build
--- a/projects/dashboard_components/build
+++ b/projects/dashboard_components/build
@@ -1,5 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-. venv/bin/activate
-npm run build
-python3 setup.py sdist bdist_wheel
+if ! npm run build; then
+	ove-echo error "'npm run build' failed"
+	exit 1
+elif ! python3 setup.py sdist bdist_wheel; then
+	ove-echo error "'python3 setup.py sdist bdist_wheel' failed"
+	exit 1
+fi
diff --git a/projects/dashboard_components/install b/projects/dashboard_components/install
--- a/projects/dashboard_components/install
+++ b/projects/dashboard_components/install
@@ -1,4 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-pip install dist/tep_dashboard-0.0.1.tar.gz
-
+if ! pip3 install --user dist/tep_dashboard-0.0.1.tar.gz; then
+	ove-echo error "'pip3 install dist/tep_dashboard-0.0.1.tar.gz' failed"
+	exit 1
+fi
